// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ACKNotification.proto

package out

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ACKNotification struct {
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	JoinEui              string   `protobuf:"bytes,2,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Fcnt                 uint32   `protobuf:"varint,4,opt,name=fcnt,proto3" json:"fcnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKNotification) Reset()         { *m = ACKNotification{} }
func (m *ACKNotification) String() string { return proto.CompactTextString(m) }
func (*ACKNotification) ProtoMessage()    {}
func (*ACKNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e7dbb9c26e4095, []int{0}
}

func (m *ACKNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACKNotification.Unmarshal(m, b)
}
func (m *ACKNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACKNotification.Marshal(b, m, deterministic)
}
func (m *ACKNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACKNotification.Merge(m, src)
}
func (m *ACKNotification) XXX_Size() int {
	return xxx_messageInfo_ACKNotification.Size(m)
}
func (m *ACKNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_ACKNotification.DiscardUnknown(m)
}

var xxx_messageInfo_ACKNotification proto.InternalMessageInfo

func (m *ACKNotification) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *ACKNotification) GetJoinEui() string {
	if m != nil {
		return m.JoinEui
	}
	return ""
}

func (m *ACKNotification) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *ACKNotification) GetFcnt() uint32 {
	if m != nil {
		return m.Fcnt
	}
	return 0
}

func init() {
	proto.RegisterType((*ACKNotification)(nil), "out.ACKNotification")
}

func init() { proto.RegisterFile("ACKNotification.proto", fileDescriptor_c7e7dbb9c26e4095) }

var fileDescriptor_c7e7dbb9c26e4095 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x75, 0x74, 0xf6, 0xf6,
	0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xce, 0x2f, 0x2d, 0x51, 0x2a, 0xe7, 0xe2, 0x47, 0x93, 0x15, 0x12, 0xe7, 0x62,
	0x4f, 0x49, 0x2d, 0x8b, 0x4f, 0x2d, 0xcd, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4b,
	0x49, 0x2d, 0x73, 0x2d, 0xcd, 0x14, 0x92, 0xe4, 0xe2, 0xc8, 0xca, 0xcf, 0xcc, 0x03, 0xcb, 0x30,
	0x81, 0x65, 0xd8, 0x41, 0x7c, 0x90, 0x94, 0x0c, 0x17, 0x67, 0x51, 0x6a, 0x5a, 0x6a, 0x51, 0x6a,
	0x5e, 0x72, 0xaa, 0x04, 0x33, 0x58, 0x0e, 0x21, 0x20, 0x24, 0xc4, 0xc5, 0x92, 0x96, 0x9c, 0x57,
	0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1b, 0x04, 0x66, 0x27, 0xb1, 0x81, 0x1d, 0x61, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x92, 0x54, 0x1d, 0xe1, 0x9d, 0x00, 0x00, 0x00,
}
