// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DataDownPayload.proto

package out

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataDownPayload struct {
	DevEui               []byte   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Confirmed            bool     `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Fport                int32    `protobuf:"varint,4,opt,name=fport,proto3" json:"fport,omitempty"`
	Reference            string   `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	ForceFrequencyOffset int64    `protobuf:"varint,6,opt,name=force_frequency_offset,json=forceFrequencyOffset,proto3" json:"force_frequency_offset,omitempty"`
	ForceGatewayId       string   `protobuf:"bytes,7,opt,name=force_gateway_id,json=forceGatewayId,proto3" json:"force_gateway_id,omitempty"`
	ForceSlot            int32    `protobuf:"varint,8,opt,name=force_slot,json=forceSlot,proto3" json:"force_slot,omitempty"`
	ForceSpreadFactor    int32    `protobuf:"varint,9,opt,name=force_spread_factor,json=forceSpreadFactor,proto3" json:"force_spread_factor,omitempty"`
	ForceBandWidth       int32    `protobuf:"varint,10,opt,name=force_band_width,json=forceBandWidth,proto3" json:"force_band_width,omitempty"`
	Expires              int32    `protobuf:"varint,11,opt,name=expires,proto3" json:"expires,omitempty"`
	Priority             int32    `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	Multicast            bool     `protobuf:"varint,13,opt,name=multicast,proto3" json:"multicast,omitempty"`
	GroupId              int32    `protobuf:"varint,14,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Fcnt                 int32    `protobuf:"varint,15,opt,name=fcnt,proto3" json:"fcnt,omitempty"`
	RfRetion             string   `protobuf:"bytes,16,opt,name=rf_retion,json=rfRetion,proto3" json:"rf_retion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDownPayload) Reset()         { *m = DataDownPayload{} }
func (m *DataDownPayload) String() string { return proto.CompactTextString(m) }
func (*DataDownPayload) ProtoMessage()    {}
func (*DataDownPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f1bcbdb2d835a7, []int{0}
}

func (m *DataDownPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDownPayload.Unmarshal(m, b)
}
func (m *DataDownPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDownPayload.Marshal(b, m, deterministic)
}
func (m *DataDownPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDownPayload.Merge(m, src)
}
func (m *DataDownPayload) XXX_Size() int {
	return xxx_messageInfo_DataDownPayload.Size(m)
}
func (m *DataDownPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDownPayload.DiscardUnknown(m)
}

var xxx_messageInfo_DataDownPayload proto.InternalMessageInfo

func (m *DataDownPayload) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DataDownPayload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataDownPayload) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *DataDownPayload) GetFport() int32 {
	if m != nil {
		return m.Fport
	}
	return 0
}

func (m *DataDownPayload) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *DataDownPayload) GetForceFrequencyOffset() int64 {
	if m != nil {
		return m.ForceFrequencyOffset
	}
	return 0
}

func (m *DataDownPayload) GetForceGatewayId() string {
	if m != nil {
		return m.ForceGatewayId
	}
	return ""
}

func (m *DataDownPayload) GetForceSlot() int32 {
	if m != nil {
		return m.ForceSlot
	}
	return 0
}

func (m *DataDownPayload) GetForceSpreadFactor() int32 {
	if m != nil {
		return m.ForceSpreadFactor
	}
	return 0
}

func (m *DataDownPayload) GetForceBandWidth() int32 {
	if m != nil {
		return m.ForceBandWidth
	}
	return 0
}

func (m *DataDownPayload) GetExpires() int32 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *DataDownPayload) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *DataDownPayload) GetMulticast() bool {
	if m != nil {
		return m.Multicast
	}
	return false
}

func (m *DataDownPayload) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *DataDownPayload) GetFcnt() int32 {
	if m != nil {
		return m.Fcnt
	}
	return 0
}

func (m *DataDownPayload) GetRfRetion() string {
	if m != nil {
		return m.RfRetion
	}
	return ""
}

func init() {
	proto.RegisterType((*DataDownPayload)(nil), "out.DataDownPayload")
}

func init() { proto.RegisterFile("DataDownPayload.proto", fileDescriptor_a6f1bcbdb2d835a7) }

var fileDescriptor_a6f1bcbdb2d835a7 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x86, 0x15, 0xf6, 0x2b, 0x19, 0x4a, 0x5b, 0x4c, 0x81, 0xe1, 0x4b, 0x8a, 0x38, 0xe5, 0xd4,
	0x0b, 0xfc, 0x02, 0x54, 0x8a, 0x7a, 0x02, 0x85, 0x03, 0xc7, 0xc8, 0x8d, 0xc7, 0xc5, 0xd2, 0xd6,
	0x0e, 0xb3, 0x93, 0x2e, 0xf9, 0x09, 0xfc, 0x6b, 0x94, 0x31, 0xed, 0x4a, 0xdc, 0xfc, 0x3e, 0xcf,
	0x6b, 0x3b, 0x99, 0x04, 0x9e, 0x5f, 0x58, 0xb1, 0x17, 0x69, 0x1f, 0xbf, 0xd9, 0x69, 0x9b, 0xac,
	0x3b, 0x1f, 0x38, 0x49, 0x32, 0x8b, 0x34, 0xca, 0xfb, 0x3f, 0x4b, 0x38, 0xf9, 0x4f, 0x9b, 0x97,
	0xb0, 0x71, 0x74, 0xd7, 0xd1, 0x18, 0xb0, 0xa8, 0x8b, 0xe6, 0xa8, 0x5d, 0x3b, 0xba, 0xfb, 0x3c,
	0x06, 0x63, 0x60, 0xe9, 0xac, 0x58, 0x7c, 0xa4, 0x54, 0xd7, 0xe6, 0x2d, 0x54, 0x7d, 0x8a, 0x3e,
	0xf0, 0x2d, 0x39, 0x5c, 0xd4, 0x45, 0x53, 0xb6, 0x07, 0x60, 0xce, 0x60, 0xe5, 0x87, 0xc4, 0x82,
	0xcb, 0xba, 0x68, 0x56, 0x6d, 0x0e, 0xf3, 0x1e, 0x26, 0x4f, 0x4c, 0xb1, 0x27, 0x5c, 0xd5, 0x45,
	0x53, 0xb5, 0x07, 0x60, 0x3e, 0xc2, 0x0b, 0x9f, 0xb8, 0xa7, 0xce, 0x33, 0xfd, 0x1a, 0x29, 0xf6,
	0x53, 0x97, 0xbc, 0xdf, 0x91, 0xe0, 0xba, 0x2e, 0x9a, 0x45, 0x7b, 0xa6, 0xf6, 0xf2, 0x5e, 0x7e,
	0x55, 0x67, 0x1a, 0x38, 0xcd, 0xbb, 0x6e, 0xac, 0xd0, 0xde, 0x4e, 0x5d, 0x70, 0xb8, 0xd1, 0xa3,
	0x8f, 0x95, 0x7f, 0xc9, 0xf8, 0xca, 0x99, 0x77, 0x00, 0xb9, 0xb9, 0xdb, 0x26, 0xc1, 0x52, 0x1f,
	0xac, 0x52, 0xf2, 0x7d, 0x9b, 0xc4, 0x9c, 0xc3, 0xb3, 0x7f, 0x7a, 0x60, 0xb2, 0xae, 0xf3, 0xb6,
	0x97, 0xc4, 0x58, 0x69, 0xef, 0x69, 0xee, 0xa9, 0xb9, 0x54, 0x71, 0xb8, 0xf8, 0xda, 0x46, 0xd7,
	0xed, 0x83, 0x93, 0x9f, 0x08, 0x5a, 0xce, 0x17, 0x7f, 0xb2, 0xd1, 0xfd, 0x98, 0xa9, 0x41, 0xd8,
	0xd0, 0xef, 0x21, 0x30, 0xed, 0xf0, 0xb1, 0x16, 0xee, 0xa3, 0x79, 0x0d, 0xe5, 0xc0, 0x21, 0x71,
	0x90, 0x09, 0x8f, 0x54, 0x3d, 0xe4, 0x79, 0x58, 0xb7, 0xe3, 0x56, 0x42, 0x6f, 0x77, 0x82, 0x4f,
	0xf2, 0x80, 0x1f, 0x80, 0x79, 0x05, 0xe5, 0x0d, 0xa7, 0x71, 0x98, 0x5f, 0xf7, 0x38, 0x1f, 0xaa,
	0xf9, 0xca, 0xcd, 0x5f, 0xcb, 0xf7, 0x51, 0xf0, 0x44, 0xb1, 0xae, 0xcd, 0x1b, 0xa8, 0xd8, 0x77,
	0x4c, 0x12, 0x52, 0xc4, 0x53, 0x1d, 0x4f, 0xc9, 0xbe, 0xd5, 0x7c, 0xbd, 0xd6, 0xff, 0xe2, 0xc3,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x19, 0xd8, 0xa0, 0x30, 0x02, 0x00, 0x00,
}
