// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JoinNotification.proto

package out

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinNotification struct {
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	JoinEui              string   `protobuf:"bytes,2,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	DevAddr              string   `protobuf:"bytes,3,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	Mac                  string   `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	Rssi                 int32    `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinNotification) Reset()         { *m = JoinNotification{} }
func (m *JoinNotification) String() string { return proto.CompactTextString(m) }
func (*JoinNotification) ProtoMessage()    {}
func (*JoinNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_13b9edd0095850c9, []int{0}
}

func (m *JoinNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinNotification.Unmarshal(m, b)
}
func (m *JoinNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinNotification.Marshal(b, m, deterministic)
}
func (m *JoinNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinNotification.Merge(m, src)
}
func (m *JoinNotification) XXX_Size() int {
	return xxx_messageInfo_JoinNotification.Size(m)
}
func (m *JoinNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinNotification.DiscardUnknown(m)
}

var xxx_messageInfo_JoinNotification proto.InternalMessageInfo

func (m *JoinNotification) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

func (m *JoinNotification) GetJoinEui() string {
	if m != nil {
		return m.JoinEui
	}
	return ""
}

func (m *JoinNotification) GetDevAddr() string {
	if m != nil {
		return m.DevAddr
	}
	return ""
}

func (m *JoinNotification) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *JoinNotification) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func init() {
	proto.RegisterType((*JoinNotification)(nil), "out.JoinNotification")
}

func init() { proto.RegisterFile("JoinNotification.proto", fileDescriptor_13b9edd0095850c9) }

var fileDescriptor_13b9edd0095850c9 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf3, 0xca, 0xcf, 0xcc,
	0xf3, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2f, 0x2d, 0x51, 0x6a, 0x67, 0xe4, 0x12, 0x40, 0x97, 0x17, 0x12,
	0xe7, 0x62, 0x4f, 0x49, 0x2d, 0x8b, 0x4f, 0x2d, 0xcd, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0x4b, 0x49, 0x2d, 0x73, 0x2d, 0xcd, 0x14, 0x92, 0xe4, 0xe2, 0xc8, 0xca, 0xcf, 0xcc, 0x03,
	0xcb, 0x30, 0x81, 0x65, 0xd8, 0x41, 0x7c, 0xa8, 0x14, 0x48, 0x4f, 0x62, 0x4a, 0x4a, 0x91, 0x04,
	0x33, 0x44, 0x2a, 0x25, 0xb5, 0xcc, 0x31, 0x25, 0xa5, 0x48, 0x48, 0x80, 0x8b, 0x39, 0x37, 0x31,
	0x59, 0x82, 0x05, 0x2c, 0x0a, 0x62, 0x0a, 0x09, 0x71, 0xb1, 0x14, 0x15, 0x17, 0x67, 0x4a, 0xb0,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x57, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0x54, 0x9d, 0x69, 0xaf, 0x00, 0x00, 0x00,
}
