// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MACCommand.proto

package out

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MACCommand struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MACCommand) Reset()         { *m = MACCommand{} }
func (m *MACCommand) String() string { return proto.CompactTextString(m) }
func (*MACCommand) ProtoMessage()    {}
func (*MACCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b0ee73bfca5a97, []int{0}
}

func (m *MACCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MACCommand.Unmarshal(m, b)
}
func (m *MACCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MACCommand.Marshal(b, m, deterministic)
}
func (m *MACCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MACCommand.Merge(m, src)
}
func (m *MACCommand) XXX_Size() int {
	return xxx_messageInfo_MACCommand.Size(m)
}
func (m *MACCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_MACCommand.DiscardUnknown(m)
}

var xxx_messageInfo_MACCommand proto.InternalMessageInfo

func (m *MACCommand) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MACCommand) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MACCommand)(nil), "out.MACCommand")
}

func init() { proto.RegisterFile("MACCommand.proto", fileDescriptor_b8b0ee73bfca5a97) }

var fileDescriptor_b8b0ee73bfca5a97 = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf0, 0x75, 0x74, 0x76,
	0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2f,
	0x2d, 0x51, 0xb2, 0xe0, 0xe2, 0x42, 0x48, 0x08, 0x09, 0x70, 0x31, 0x27, 0x67, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9,
	0x89, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x14, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xf2, 0xdc, 0xab, 0x59, 0x00, 0x00, 0x00,
}
